version: "3.9"
services:
  scraper:
    build: ./scraper
    container_name: pandarank-scraper
    environment:
      - OPENAI_SESSION_TOKEN=${OPENAI_SESSION_TOKEN}
      - OPENAI_EMAIL=${OPENAI_EMAIL}
      - OPENAI_PWD=${OPENAI_PWD}
      - SCRAPE_INTERVAL_SEC=${SCRAPE_INTERVAL_SEC:-600}
      - DB_DSN=postgresql://scraper:secret@db:5432/chatlogs
      - TZ=${TZ:-Asia/Tokyo}
      - QUESTION_POOL_PATH=/app/data/questions.yaml
      - HEADLESS=${HEADLESS:-true}
      - DEMO_MODE=${DEMO_MODE:-false}
    depends_on:
      - db
    ports:
      - "${SCRAPER_PORT:-8080}:8080"  # metrics / healthz
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=scraper
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=chatlogs
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-5432}:5432"

  api:
    build: ./api
    container_name: pandarank-api
    environment:
      - DB_DSN=postgresql://scraper:secret@db:5432/chatlogs
    depends_on:
      - db
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: pandarank-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata: